# -*- coding: utf-8 -*-
"""housepredictLinearEQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PErNG_h6KVwcNuPfaRU3xC4kGLFoDA1N
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

home={
    "area":[2600,3000,3200,3600,4000],
    "bedrooms":[3,4,3,3,5],
    "age":[20,15,18,30,8],
    "price":[550000,565000,610000,595000,760000]
}

homedf=pd.DataFrame(home)

homedf.to_csv("homedata.csv",index=False)

homedf

homedf.bedrooms.median()

import math
median_bedrooms= math.floor(homedf.bedrooms.median())
median_bedrooms

homedf.bedrooms.fillna(median_bedrooms)

homedf

reg= linear_model.LinearRegression()
reg.fit(homedf[['area','bedrooms','age']],homedf.price)

reg.coef_

reg.predict([[2500,4,5]])

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(homedf.area,homedf.price,color='red',marker='+')
plt.plot(homedf.area,reg.predict(homedf[['area','bedrooms','age']]),color='blue')

